spring:
#  session:
#    redis:
#      namespace: login_user
#
#    timeout: 3600
#    store-type: redis
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kss-zixun-db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    password: 2002310gq
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 6
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0

  map:
    name: name
    age: age
  list:
    - 1
    - 2
    - 3
    - 4
