spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kss-zixun-db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    password: 2002310gq
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
a
