server:
  port: 10001
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 5MB
      file-size-threshold: 20MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
alipay:
  res:
    age: 王五
    id: 88120
    name: 赵家村